// Copyright 2020-2021 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/*
 * CMAiW82AL_V1.0 board GPIO defaults.
 * Keep the SDK and ai_xiaozhi reference trees read-only; board-specific
 * pinmux work belongs in this project.
 */
#define GPIO_DEFAULT_DEV_CONFIG  \
{\
	{GPIO_0,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2C1_SCL,        GPIO_IO_DISABLE,    GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_1,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2C1_SDA,        GPIO_IO_DISABLE,    GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_2,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI1_CLK,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_3,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI1_CSN,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_4,  GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI1_IO0,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_5,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_6,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_OUTPUT_ENABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_7,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_8,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_OUTPUT_ENABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_9,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_OUTPUT_ENABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_12, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_13, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_14, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SPI0_SCK,        GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_15, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SPI0_CSN,        GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_16, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SPI0_MOSI,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_17, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_SPI0_MISO,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_18, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_OUTPUT_ENABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_19, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_OUTPUT_ENABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_20, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2C0_SCL,        GPIO_IO_DISABLE,    GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_21, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_I2C0_SDA,        GPIO_IO_DISABLE,    GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_22, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI0_CLK,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_23, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI0_CSN,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_24, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_QSPI0_IO0,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_25, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_PWM5,            GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_26, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_27, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_MCLK,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_28, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_OUTPUT_ENABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_29, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PCLK,       GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_30, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_HSYNC,      GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_31, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_VSYNC,      GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_32, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA0,    GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_33, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA1,    GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_34, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA2,    GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_35, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA3,    GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_36, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA4,    GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_37, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA5,    GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_38, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA6,    GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_39, GPIO_SECOND_FUNC_ENABLE,  GPIO_DEV_JPEG_PXDATA7,    GPIO_IO_DISABLE,    GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_40, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_OUTPUT_ENABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_41, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_42, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_IO_DISABLE,    GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_43, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_IO_DISABLE,    GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_44, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_45, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_46, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_47, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_48, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_49, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_50, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_OUTPUT_ENABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_51, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_52, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_53, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_OUTPUT_ENABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL,     GPIO_LOW_POWER_KEEP_OUTPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_54, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
	{GPIO_55, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID,         GPIO_INPUT_ENABLE,  GPIO_PULL_UP_EN,  GPIO_INT_DISABLE, GPIO_INT_TYPE_FALLING_EDGE,  GPIO_LOW_POWER_KEEP_INPUT_STATUS,  GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_DISABLE},\
}

#ifdef __cplusplus
}
#endif
